<?php
$properties = [
    [
        "id" => 1,
        "type" => "apartment",
        "name" => "Central City Apartment",
        "lat" => 55.6796,
        "lng" => 12.5646,
        "price" => "1.200.000 DKK",
        "image" => "images/apartment2.jpg",
    ],
    [
        "id" => 2,
        "type" => "villa",
        "name" => "Spacious Family Villa",
        "lat" => 55.6899,
        "lng" => 12.5267,
        "price" => "3.500.000 DKK",
        "image" => "images/villa.jpg",
    ],
    [
        "id" => 3,
        "type" => "andelslejlighed",
        "name" => "Charming cooperative apartment",
        "lat" => 55.6820,
        "lng" => 12.5400,
        "price" => "2.000.000 DKK",
        "image" => "images/cooperative.jpg",
    ],
    [
        "id" => 4,
        "type" => "land",
        "name" => "Open Land Plot",
        "lat" => 55.6850,
        "lng" => 12.5500,
        "price" => "750.000 DKK",
        "image" => "images/land.jpg",
    ],
    [
        "id" => 5,
        "type" => "apartment",
        "name" => "Modern City Apartment",
        "lat" => 55.6712,
        "lng" => 12.5534,
        "price" => "2.100.000 DKK",
        "image" => "images/apartment3.jpg",
    ],
    [
        "id" => 6,
        "type" => "villa",
        "name" => "Family Villa with Garden",
        "lat" => 55.7023,
        "lng" => 12.5001,
        "price" => "4.800.000 DKK",
        "image" => "images/villa2.jpg",
    ],
    [
        "id" => 7,
        "type" => "andelslejlighed",
        "name" => "Cozy Cooperative Apartment",
        "lat" => 55.6904,
        "lng" => 12.5618,
        "price" => "1.650.000 DKK",
        "image" => "images/cooperative2.jpg",
    ],
    [
        "id" => 8,
        "type" => "land",
        "name" => "Scenic Land Plot",
        "lat" => 55.6967,
        "lng" => 12.6123,
        "price" => "950.000 DKK",
        "image" => "images/land2.jpg",
    ],
];
?>